name: elife2024
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - seaborn
  - scikit-learn
  - ipykernel
  - pyqt
  - pip
  - pip:
      - pickle4
      - git+https://github.com/crheller/dDR.git
      - git+https://github.com/LBHB/NEMS.git

